apiVersion: v1
kind: Service
metadata:
  name: rag-python-api
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: rag-python-api
  ports:
    - port: 80
      targetPort: {{ .Values.rag-python-api.port }}