apiVersion: v1
kind: Secret
metadata:
  name: rag-app-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.postgres.user }}
  DB_PASS: {{ .Values.postgres.password }}
  DB_NAME: {{ .Values.postgres.dbname }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey }}